### ISSUE TITLE
Refactor metaP aggregation

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-aggregator#26]
We've decided to rewrite how the metaproteomics data are being aggregated.

Goals of the script
1) Write to the `functional_aggreagation_agg` collection
2) Use the API, reduce reliance with direct connection to MongoDB
3) Access the raw protein reports (not just the mongo data) to generate the records
4) Validate and submit data via API

**Comment by aclum** [comment]
2 & 4 overlaps with https://github.com/microbiomedata/nmdc-aggregator/issues/11 so feel free to close or assign to yourself as a subtask.
